### ISSUE TITLE
Error on Launching HM5.Server.exe

### ISSUE THREAD

**Issue by devildwarf** [LennardF1989/Hitman-5-Server#2]
Just tested the first release and i get this error on launching it
`
Unhandled exception. System.InvalidOperationException: Unable to configure HTTPS endpoint. 
No server certificate was specified, and the default developer certificate could not be found or is out of date.
To generate a developer certificate run 'dotnet dev-certs https'. To trust the certificate (Windows and macOS only) run 'dotnet dev-certs https --trust'.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Reload()
   at Microsoft.AspNetCore.Server.Kestrel.KestrelConfigurationLoader.Load()
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication 1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String startupMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.Run(IWebHost host)
   at HM5.Server.Program.Main(String[] args) in G:\Projects\Lennard\Temp\HM5\Src\HM5.Server\Program.cs:line 9
`
If i run "dotnet dev-certs https" it does fix the problem, i tested it on 2 PC's and both did this and a VM which also did this.

EDIT:- If i remove the https from the appsettings.json it does fix the problem too (tested on VM)

**Comment by AnthonyFuller** [comment]
Just looks like no cert was generated. Not sure if an SSL connection is even required.

**Comment by LennardF1989** [comment]
It is not, I published a [fix](https://github.com/LennardF1989/Hitman-5-Server/releases/tag/v1.0.1) that should just make it run on port 80.
